const videosTypes = {
    ADD_NEW_VIDEO_START: 'ADD_NEW_VIDEO_START',
    FETCH_VIDEOS_START: 'FETCH_VIDEOS_START',
    SET_VIDEOS: 'SET_VIDEOS',
    FETCH_FOLLOWINGVIDEOS_START: 'FETCH_FOLLOWINGVIDEOS_START',
    SET_FOLLOWINGVIDEOS: 'SET_FOLLOWINGVIDEOS',
    DELETE_VIDEO_START: 'DELETE_VIDEO_START',
    FETCH_VIDEO_START: 'FETCH_VIDEO_START',
    SET_VIDEO: 'SET_VIDEO'
}

export default videosTypes