const imagesTypes = {
    ADD_NEW_IMAGE_START: 'ADD_NEW_IMAGE_START',
    FETCH_IMAGES_START: 'FETCH_IMAGES_START',
    SET_IMAGES: 'SET_IMAGES',
    DELETE_IMAGE_START: 'DELETE_IMAGE_START',
    FETCH_IMAGE_START: 'FETCH_IMAGE_START',
    SET_IMAGE: 'SET_IMAGE'
}

export default imagesTypes